In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.1.0+cu121


# Tensors- n-d array and support GPU calculation
## similar to numpy array

In [ ]:
np_a1 = np.array([1, 2, 3, 4])
np_a2 = np.array([5, 6, 7, 8])
torch_tensor_1 = torch.tensor([1, 2, 3, 4])
torch_tensor_2 = torch.tensor([5 ,6 ,7, 8])

print(np_a1, np_a2)
print(torch_tensor_1, torch_tensor_2)

[1 2 3 4] [5 6 7 8]
tensor([1, 2, 3, 4]) tensor([5, 6, 7, 8])


In [ ]:
print(np_a1.shape)
print(torch_tensor_1.shape)
print (torch_tensor_1.size()) # size() and shape operation is identical in torch

(4,)
torch.Size([4])
torch.Size([4])


In [ ]:
# concat 2 arrays

merge = np.concatenate([np_a1,np_a1],axis=0)
print(merge)

print("-------------------")

torch_concate= torch.cat([torch_tensor_1, torch_tensor_2], dim=0)
print (torch_concate)

[1 2 3 4 1 2 3 4]
-------------------
tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [ ]:
# reshape

np_reshaped = merge.reshape(4,2)
print(np_reshaped)

torch_reshaped = torch_concate.view(4,2)
print(torch_reshaped)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
x = np.array([1, 2, 3])
x_repeat = x.repeat(3) #repeat each em=lemet for 3 times in new array

print ('----numpy----')
print (x)
print (x_repeat)

x = torch.tensor([1, 2, 3])
x_repeat = x.repeat(2)  #small difference in repeat

print ('----torch----')
print (x)
print (x_repeat)

# To obtain the same result with np.repeat (will skip explanation: you should be proficient with reshaping operations)
x_repeat = x.repeat_interleave(2)
print (x_repeat)

----numpy----
[1 2 3]
[1 1 1 2 2 2 3 3 3]
----torch----
tensor([1, 2, 3])
tensor([1, 2, 3, 1, 2, 3])
tensor([1, 1, 2, 2, 3, 3])


In [ ]:
# similar manipulation operation: stack & repeat
x = torch.tensor([1, 2, 3])
x_repeat = x.repeat(4)
x_stack = torch.stack([x, x, x, x])

print (x_repeat)
print (x_stack)
print (x_repeat.view(4, 3)) # reshape x

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


# Using GPU for tensor operations

In [ ]:
print(torch.cuda.is_available())  # Is GPU accessible?

True


In [ ]:
a = torch.ones(3)
b = torch.randn(100, 50, 3)

# b conatins 100 outer list with each containing 50 and each with 3 values in list

print(a)
print(b[0])
print(b.shape)

tensor([1., 1., 1.])
tensor([[-0.5476, -0.0094,  0.3635],
        [-0.6909, -1.5198, -0.9074],
        [-0.5184,  0.3886,  0.5978],
        [ 0.0459, -0.8069,  0.7332],
        [-1.5943, -1.0319,  0.3015],
        [-0.5568,  0.5585, -1.7527],
        [ 0.6068,  0.2105, -0.0142],
        [-0.0273, -0.5850,  0.4500],
        [-0.3465, -1.2319, -0.1080],
        [-0.5219,  0.3729,  0.1086],
        [-0.6950, -0.2002, -0.6011],
        [-1.4381,  0.1396, -1.1387],
        [ 0.4394, -1.2552,  0.4324],
        [ 0.2013, -0.2290,  0.8440],
        [-0.3426, -0.4806,  0.6396],
        [-1.8838,  1.0137, -0.4016],
        [-0.0141, -0.1519,  0.9413],
        [ 0.9987,  0.2176, -0.2497],
        [ 0.5375,  0.9703,  0.3179],
        [ 0.8479, -0.9756, -0.2072],
        [-0.1054, -1.5645, -0.5623],
        [ 1.5403, -0.5006, -1.5030],
        [-0.2007, -0.0328,  1.6662],
        [ 1.1336,  0.7958, -0.2896],
        [ 0.5665,  0.1580,  0.6591],
        [ 0.0045,  0.7290,  1.4609],
        [ 1.4440,

In [ ]:
print(a.device)
print(b.device)

cpu
cpu


In [ ]:
c = a + b
print(c.device)

cpu


In [ ]:
a = a.to('cuda')
b = b.to('cuda')

In [ ]:

print(a.device)
print(b.device)

cuda:0
cuda:0


In [ ]:
c = a + b
print(c.device)


cuda:0


In [ ]:
c = c.to('cpu')
print(c.device)


cpu


# Autograd

In [ ]:
# The autograd package provides automatic differentiation for all operations on Tensors.

# torch.Tensor is the central class of the package. If you set its attribute requires_grad as True,
# it starts to track all operations on it.

# When you finish your computation you can call .backward() and have all the gradients computed automatically.

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
z = y*y*3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [ ]:
output = z.mean()
print(output)

tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
y.retain_grad()
z.retain_grad()
output.backward()

In [ ]:
print(z.grad)


tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [ ]:
print(y.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
# Efficient inference (testing) with torch.no_grad()

In [ ]:
with torch.no_grad():
    x = torch.ones(2, 2, requires_grad=True)
    y = x + 2
    z = y * y * 3
    out = z.mean()

In [ ]:
out


tensor(27.)